.catalog:
  name: "Portus"
  version: "v2.3.1-3.1"
  description: "Docker Registry with GUI"
  uuid: registry-3
  questions:
    - variable: "RPORT"
      label: "Registry Port"
      description: "Port on which to run the registry service"
      default: 5000
      required: true
      type: "int"
    - variable: "PPORT"
      label: "Admin Port"
      description: "Port on which to run the SSL Portus administration service and API"
      default: 443
      required: true
      type: "int"
    - variable: "DBPASSWORD"
      label: "DB Password"
      description: "Password for Portus database access, must be 8 characters or longer"
      required: true
      default: password
      type: "password"
    - variable: "ROOTPASSWORD"
      label: "DB Root Password"
      description: "Root Password for MySQL database, must be 8 characters or longer.  This is not normally used."
      required: true
      default: password
      type: "password"
    - variable: "DOMAIN"
      label: "FQDN"
      description: "FQDN of server.  This should be the CN in the certificates and will be the URL to contact the Registry and Web interface"
      required: true
      default: portus.staging.teco.edu
      type: "string"
    - variable: "LDAPHOST"
      label: "LDAP Server"
      description: "The FQDN of the LDAP server (if LDAP authentication is being used)"
      required: false
      default: "ldap.teco.edu"
      type: "string"
    - variable: "LDAPPORT"
      label: "LDAP Server port"
      description: "The port number on the LDAP server (if LDAP authentication is being used)"
      required: false
      default: 636
      type: "int"
    - variable: "LDAPTLS"
      label: "LDAP TLS"
      description: "The TLS option for the LDAP server (if LDAP authentication is being used)"
      required: false
      default: "simple_tls"
      type: "enum"
      options:
        - starttls
        - simple_tls
        - plain
    - variable: "LDAPBASE"
      label: "LDAP Base DN"
      description: "The Base DN for User lookups on the LDAP server (if LDAP authentication is being used)"
      required: false
      default: "ou=People,dc=teco,dc=edu"
      type: "string"
    - variable: "LDAPBIND"
      label: "LDAP Bind enabled"
      description: "Should an authenticated Bind be used to access LDAP (if LDAP authentication is being used)"
      required: false
      default: true
      type: "boolean"
    - variable: "LDAPBINDDN"
      label: "LDAP Bind DN"
      description: "The DN to use for binding to the LDAP server (if LDAP authentication is being used with Bind enabled)"
      required: false
      default: "uid=testuser,ou=People,dc=teco,dc=edu"
      type: "string"
    - variable: "LDAPBINDPASS"
      label: "LDAP Bind Password"
      description: "The password to use for binding to the LDAP server (if LDAP authentication is being used with Bind enabled)"
      required: false
      default: "password"
      type: "password"
    - variable: "LDAPBINDUID"
      label: "LDAP Bind UID"
      description: "The method of defining the user (if LDAP authentication is being used with Bind enabled)"
      required: false
      default: "cn"
      type: "enum"
      options:
        - cn
        - sAMAccountName
db:
  scale: 1
sslproxy:
  scale: 1
lb:
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
registry:
  scale: 1
portus:
  scale: 1
