version: '2'
services:
 etcdbrowser:
   image: localhost:5000/etcd-browser
   ports:
   - 49502:49502/tcp
   labels:
     rap.port: '49502'
     rap.host: config.app-registry.staging.teco.edu

 etcd:
   image: quay.io/coreos/etcd
   environment:
     ETCD_CORS: '*'
   ports:
   - 49501:49501/tcp
   labels:
     rap.port: '49501'
     rap.host: app-registry.staging.teco.edu
   command:
   - /usr/local/bin/etcd
   - "-advertise-client-urls=http://0.0.0.0:49501"
   - "-listen-client-urls=http://0.0.0.0:49501"
