version: '2'
services:
  gitlab:
    image: gitlab/gitlab-ce:latest
    environment:
      GITLAB_OMNIBUS_CONFIG: "external_url 'http://gitlab.staging.teco.edu'\ngitlab_rails['git_timeout']\
        \ = 600\nnginx['keepalive_timeout'] = 300\nunicorn['worker_timeout'] = 300\
        \                        #to reduce effect of network glitches\nunicorn['worker_processes']\
        \ = 3\nnginx['listen_port'] = 80\nnginx['client_max_body_size'] = '300m' \
        \       \ngitlab_rails['ldap_enabled'] = true\ngitlab_rails['ldap_servers']\
        \ = YAML.load <<-EOS\n main:\n  label: 'LDAP'\n  host: 'ldap.teco.edu'\n \
        \ port: '636'\n  uid: 'uid'\n  bind_dn: 'uid=testuser,ou=People,dc=teco,dc=edu'\n\
        \  password: '#83hSAFI92ml-'\n  encryption: 'simple_tls'\n  active_directory:\
        \ 'false'\n  base: 'ou=People,dc=teco,dc=edu'\n  timeout: '10000'\n  group_base:\
        \ 'ou=Group,dc=teco,dc=edu'\n  EOS\n"
    volumes:
    - /srv/business-essentials/teco_gitlab/config:/etc/gitlab
    - /srv/business-essentials/teco_gitlab/logs:/var/log/gitlab
    - /srv/business-essentials/teco_gitlab/data:/var/opt/gitlab
    ports:
    - 11:22/tcp
    labels:
      rap.port: '80'
      rap.le_host: teco-gitlab.staging.teco.edu
      rap.client_max_body_size: 300m
      rap.host: teco-gitlab.staging.teco.edu
