version: '2'

services:

    sda-test-app:
        image: localhost:5000/test-app
        # no port declaration because the app should be isolated

    x-spsc-identity-mananger:
        image: localhost:5000/identity-manager

    x-spsc-license-mananger:
        image: localhost:5000/license-manager

    x-spsc-router:
        image: localhost:5000/router
        expose:
            - 1000
        environment:
            - VIRTUAL_HOST=sidecar.app.staging.teco.edu
            - VIRTUAL_PORT=1000
        networks:
            - default
