version: '3'

services:

    sda-test-app:
        image: localhost:5000/test-app
        # no port declaration because the app should be isolated

    x-spsc-identity-mananger:
        image: localhost:5000/identity-manager

    x-spsc-license-mananger:
        image: localhost:5000/license-manager

    x-spsc-router:
        image: localhost:5000/router
        expose:
            - 1000
        environment:
            - VIRTUAL_HOST=sidecar.app.staging.teco.edu
            - VIRTUAL_PORT=1000
        networks:
            - default
        labels:
          io.rancher.container.pull_image: always
          io.rancher.scheduler.affinity:container_label_soft: registry.portus.db=1
          registry.portus.app: 1
          rap.port: '1000'
          rap.le_host: sidecar.app.staging.teco.edu
          rap.host: sidecar.app.staging.teco.edu
